---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-alerts-channels
  namespace: d8-monitoring
{{ include "helm_lib_module_labels" (list . (dict "app" "grafana")) | indent 2 }}
data:
  notifiers.yaml: {{ .Values.prometheus.internal.grafana.alertsChannels | toYaml | b64enc }}
