# This workflow reacts to labels and restart workflows if needed.
# Cloud layout tests and deploy web are restarted only when PR is labeled.
# Validation workflow is restarted when PR is labeled or unlabeled.
name: Rerun workflows for pull request

on:
  pull_request_target:
    types: [labeled, unlabeled]
jobs:
{!{ tmpl.Exec "pull_request_info_job" . | strings.Indent 2 }!}
{!{ tmpl.Exec "git_info_job" .      | strings.Indent 2 }!}
  rerun_workflow_for_pull_request:
    name: Rerun workflow for pull request
    runs-on: ubuntu-latest
    needs:
      - git_info
      - pull_request_info
    steps:
      - name: Rerun workflow
        uses: {!{ index (ds "actions") "actions/github-script" }!}
        with:
          github-token: ${{ secrets.BOATSWAIN_GITHUB_TOKEN }}
          script: |
            const ci = require('./.github/scripts/js/ci');
            const ref = "${{ needs.pull_request_info.outputs.ref }}"
            const ci_commit_ref_name = "${{ needs.git_info.outputs.ci_commit_ref_name }}"
            return await ci.runWorkflowForPullRequest({ github, context, core, ref, ci_commit_ref_name });
