{{- if and (.Values.flantIntegration.madisonAuthKey) (and ($.Values.global.enabledModules | has "prometheus-crd") ($.Values.global.enabledModules | has "prometheus")) }}
apiVersion: deckhouse.io/v1alpha1
kind: GrafanaAlertsChannel
metadata:
  name: madison-proxy
{{ include "helm_lib_module_labels" (list . (dict "app" "madison-proxy")) | indent 2 }}
spec:
  description: "Channel to send alerts to Polk. Auto-created by flant-integration module"
  type: PrometheusAlertManager
  # we do not need receive [OK] alerts in madison (and do not want show in polk)
  disableResolveMessage: true
  # todo think about disable default from config
  isDefault: true
  alertManager:
    address: {{ printf "http://madison-proxy.d8-monitoring.svc.%s:8080" .Values.global.discovery.clusterDomain | quote }}
{{- end }}
