---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ebpf-exporter
  namespace: d8-monitoring
{{ include "helm_lib_module_labels" (list . (dict "app" "ebpf-exporter" "prometheus" "main")) | indent 2 }}
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: ebpf-exporter
  namespaceSelector:
    matchNames:
    - d8-monitoring
  podMetricsEndpoints:
  - port: https-metrics
    scheme: https
    scrapeTimeout: 20s
    tlsConfig:
      insecureSkipVerify: true
      cert:
        secret:
          name: prometheus-scraper-tls
          key: tls.crt
      keySecret:
        name: prometheus-scraper-tls
        key: tls.key
    relabelings:
    - regex: endpoint|namespace|pod|service
      action: labeldrop
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - targetLabel: tier
      replacement: cluster
